---
abstract: 'Specialized HTTP client'
author:
  - 'Kang-min Liu & Borislav Nikolov'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  ExtUtils::MakeMaker: 6.59
dynamic_config: 0
generated_by: 'Module::Install version 1.06, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hijk
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  perl: v5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.02
x_module_name: Hijk
